#!/usr/bin/env python

class ResourceList:
    """

    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """

    def __init__(self):
        self.swaggerTypes = {
            'Items': 'list<Str>',
            'DisplayedCount': 'int',
            'SortDir': 'str',
            'TotalCount': 'int',
            'Offset': 'int',
            'SortBy': 'str',
            'Limit': 'int'
        }

        # 
        self.Items = None # list<Str>
        # 
        self.DisplayedCount = None # int
        # 
        self.SortDir = None # str
        # 
        self.TotalCount = None # int
        # 
        self.Offset = None # int
        # 
        self.SortBy = None # str
        # 
        self.Limit = None # int