class VariantHeader:
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """

    def __init__(self):
        self.swaggerTypes = {
            'Metadata': 'dict',
            'Samples': 'dict',
            'Legends': 'dict',
        }
    def __str__(self):
        return "VariantHeader: SampleCount=" + str(len(self.Samples))
    def __repr__(self):
        return str(self)

        # 
        self.Metadata    = None # dict
        # 
        self.Samples     = None # dict
        # 
        self.Legends     = None # dict
